# Generated by Django 5.2.4 on 2025-07-14 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_user_auth_method_user_last_login_alter_app_app_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('app', 'email')},
        ),
    ]
