# Generated by Django 5.2.4 on 2025-07-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=3.5, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_method',
            field=models.CharField(choices=[('oauth', 'OAuth'), ('credentials', 'Credentials'), ('magic_link', 'Email Magic Link'), ('manual', 'Manual Entry')], default='credentials', max_length=50),
        ),
    ]
